### ISSUE TITLE
Clear the form

### ISSUE THREAD

**Issue by blabno** [draperd/react-forms-processor#22]
How do I clear the form?
Let's say I want to have a form to add items to a table. Once I click the submit button then the form should be cleared so that I can add next row to the table.

**Comment by draperd** [comment]
Just to clarify the use case... you have a form that is always present on the page (e.g. it is not displayed in a modal dialog when a "New" or "Create" button is clicked) ... once the submit button is clicked you want to be able to reset the form back to it's default values without needing to recreate it?

So this also means that you want to reset the touched state of all the fields as well? (which I think explains the side-effect you were referring to in a previous PR).

Presumably the state will be managed outside of the form - e.g. once the values from a form are successfully submitted and the row added to the table a state change in some outer component would want to change props on the form to completely reset it to it's original state. Similarly if you wanted to edit an existing row you'd want to populate the form with the values of that row but still reset the touched state?

**Comment by blabno** [comment]
Correct

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by draperd** [comment]
I think in that case the correct solution would be that when a new value is passed to the form that the touched state for all the fields is reset. Does that seem like reasonable behaviour?

**Comment by draperd** [comment]
I've started looking at this but haven't yet completed this. I think that in order to successfully implement this we might want to switch from a `value` prop on the `Form` component to a `defaultValue` prop to make it more consistent and clear what is happening.

If the `defaultValue` prop changes then it would both reset the touched state of all the fields and override the current `value` in the component state. Hopefully I'll have some time to complete the work on this later in the week.

**Comment by draperd** [comment]
This issue should now be resolved and the fix available in 0.0.28 version - apologies for taking a little while to resolve it.
