### ISSUE TITLE
'disabled' attribute and 'defaultValue' attribute does not work with atlaskit renderer

### ISSUE THREAD

**Issue by prashanthmudedla** [draperd/react-forms-processor#32]
Hi Dave,

Thanks for the library. 

I am trying to use this library for a requirement to render form based on a config. I am facing two issues as of now.

1.  I have to render the same form in both create mode and edit mode. While opening the form in Edit mode, I have to pre load the form with values from the service. I am not able to achieve this with the field attribute 'defaultValue'. But I could do this by setting the 'value' attribute on Form element with the JSON data. Now, whats the purpose of the attribute 'defaultValue' on the field.

2.  I have to disable certain fields on the form when I open it in read only mode. I could not achieve this with the attribute 'disabled' on the field. Could you please let me know if it is the right way.

Below is a code sample of my app.

``` JSX
import React, { Component } from 'react';
import { Form } from 'react-forms-processor';
import { renderer, FormButton } from 'react-forms-processor-atlaskit';

export class UserDetails extends Component<UserDetailsProps, UserDetailsState> {
   const UserDetailsFormConfig = (isEditMode: boolean) => [
    {
      "id": "fname",
      "name": "fname",
      "type": "text",
      "label": "First Name",
      "description": "",
      "placeholder": "Enter First Name",
      "defaultValue": "",
      "visible": true,
      "required": true,
      "disabled": isEditMode || false,
      "requiredWhen": [],
      "shouldMatchRegex": false,
      "hasMinLength": true,
      "validWhen": {
        "lengthIsGreaterThan": {
          "length": "5",
          "message": "First name should have at least 5 characters"
        },
        "lengthIsLessThan": {
          "length": "50",
          "message": "First name cannot have more than 50 characters"
        }
      },
      "hasMaxLength": true,
      "hasNumericalRange": false,
      "shouldCompareTo": false
    }
  ]

  render() {
        let content;
        if (!this.state.isEditMode || 
            (this.state.userData && this.state.userData.fname)) {
            
            content = <PageContainer>
                <UserDetailsFormContainer>
                    <PageHeader />
                    <Form renderer={renderer} defaultFields={UserDetailsFormConfig(this.state.isEditMode)} 
                            onChange={this.onFormValueChange} value={this.state.userData}>
                        <FormButtonWrapper>
                            <FormButton label={this.state.isEditMode ? "Update Details" : "Submit Details"}
                                onClick={this.onSubmitButtonClick} />
                        </FormButtonWrapper>
                    </Form>
                </UserDetailsFormContainer>
                <JsonContainer>
                    <h3>Value</h3>
                    <p>This section shows the current value of the form.</p>
                    <PrettyPrintJson userData={this.state.userData}/>
                </JsonContainer>
            </PageContainer>;
        } else {
            content = <PageContainer>
                <NoResultsContainer>
                    <PageHeader />
                    <div>Oops, user not found!</div>
                </NoResultsContainer>
            </PageContainer>
        }

        return content;
   }

}
```

**Comment by draperd** [comment]
Hi Prasanth,

Thanks for the questions...

1. `value` vs `defaultValue` on fields and form
At the moment you're right that you would need to use the `value` prop to set a value on the Form component because at the moment there is no `defaultValue` attribute. This actually came up in my comments on #22 and #27 but I haven't elected to add a `defaultValue` prop yet although I acknowledge that this would probably be better and more consistent.

The difference between the `value` and `defaultValue` props on the field is that the `value` is used to hold the current value of a field at any point during editing of the form but the `defaultValue` is just the value that you might want to give the field as a starting point.

Really there is an issue in the Flow typing for the project where I should have one type for the field definition and another for the field instance - but I only ended up adding `defaultValue` later on once I realised my mistake and haven't tidied up the types yet.

At the moment I have been able to 'get away' with not needing that same separation at the form level but increasingly I think that I need to add it.

2. Disabling in a read only mode
In your example I would suggest passing an additional value to the form, e.g. `mode` or something similar that is passed to a field that is always hidden. Even though the field is hidden you could still use it's value to conditionally disable certain fields.

For example you could define rules like

``` JSON
"disabledWhen": [
{
  "field": "mode",
  "is": [
    'READONLY'
  ]
}]
```

...you could use the `omitWhenHidden` prop on the `mode` field so that it isn't included in the form value that is submitted.

I hope that helps, please let me know if have any further questions.

**Comment by prashanthmudedla** [comment]
Hi Dave,

Thanks for your quick reply. I will try your suggestions and close the thread.

Thanks,
Prashanth

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
