### ISSUE TITLE
error when installing via npm

### ISSUE THREAD

**Issue by driedl** [draperd/react-forms-processor#46]
Possibly I'm missing something, but following the tutorial from:
https://medium.com/@dave.draper20/how-to-create-forms-with-the-react-forms-processor-9bcdd241f502

... and simply replacing yarn with npm I get some errors:
![image](https://user-images.githubusercontent.com/3268596/52157004-c36d6680-2640-11e9-97cb-2fde14e83577.png)

Everything seems to be in place in the `node_modules` folder... all other modules work fine.

Note that I am also using Neutrino to configure my dev environment with the React preset, not "create-react-app". 

I'm running node v10.15.0 and npm v6.7.0

From the command line, when installing "react-forms-processor", I get the following error (same when i install react-forms-processor-material-ui):

> \>npm install react-forms-processor
> \>npm WARN react-forms-processor-material-ui@0.0.32 requires a peer of react-forms-processor@0.0.1 but none is installed. You must install peer dependencies yourself.

The above sounds strange to me... i installed both modules.

Any pointers?

**Comment by draperd** [comment]
Hi Dave, thanks for asking the question and apologies for taking a couple of days to get back to you. It might be that I've not packaged up the material-ui rendering library properly. Do you get the same issue with the Atlaskit rendering library at all? It would be useful if you could try that out so I know whether it's something general with your setup or just specific to that package. You could also check just to see if the native HTML renderer bundled in the core package works.

I can't think of any specific reason why using NPM instead of Yarn would make any difference!

**Comment by driedl** [comment]
Thanks for the response Dave, I figured out my issue... I took it for granted that `react-forms-processor-material-ui` exports matched that of atlaskit.  They both export `renderer` but only atlaskit exports `FormButton`.  I was thrown off course by the strange warnings npm was giving regarding peer dependency missing and also the VScode warnings about missing `.d.ts`. I incorrectly was trying to solve these errors (which are just warnings) instead of noticing the non-existent export.

I unfortunately don't know enough about packaging npm modules to provide any more help regarding these errors. Finding a configurable way to suppress them, or adding the missing metadata file could possibly make adoption of you module easier.  Regardless, thanks for a great library.  I'm looking forward to experimenting with it to see if it fits our business needs.

**Comment by draperd** [comment]
Cool, thanks for letting me know @driedl .... I had only very quickly added the Material UI renderer as an example for what would be possible. My assumption is that most users will ultimately want to be responsible for how their own forms are rendered which is why I tried to de-couple it as much as possible.

We're using the Atlaskit renderer where I work which is why I've not invested much effort in the Material renderer.

Let me know if you have any other feedback.
