### ISSUE TITLE
Is support for React Hooks on the roadmap?

### ISSUE THREAD

**Issue by driedl** [draperd/react-forms-processor#68]
Hi @draperd, I was curious if you had any plans to add support for React Hooks to gain access to the forms context instead of using ```FieldWrapper``` and  ```FormContext```. 

It seems like there is a growing trend in the React community to transition away from class-based components.

**Comment by draperd** [comment]
Hi @driedl , the answer to this is "sort of" ... this is something I'd definitely like to do and have done some prototyping to rewrite the core package using hooks and can see that they'd greatly simplify the code structure and hopefully help with some performance improvements. The prototyping work I've done so far can be found here: https://github.com/draperd/forms-with-hooks

Because of the functional approach I've taken previously it should be relatively straight forward to port all the existing form handling logic and tests to use hooks. 

However, in the past year I've switched from being a developer to a manager at work which means I have much less time to focus on projects like this. We are using this react-forms-processor in a product so it will continue to be supported but the rate of new features (and refactoring to convert to hooks) is likely to progress at a relatively slow pace.

**Comment by driedl** [comment]
@draperd, thanks for the prompt reply. I'll have a look at the prototype.

**Comment by draperd** [comment]
Cool, it's not very far along - I started it in a new project just to start learning hooks :)

**Comment by philohelp** [comment]
Hi there,
I think this package is fantastic. Building forms become so easy with a clean code - issues I had for years. I plan to use it in at least two projects. Updating to hooks would be terrific. I wish I could help, but I know nothing about Lerna and I never used the Context API. 
Thank you again !
